//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicbrainz.mmd2;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://musicbrainz.org/ns/mmd-2.0#}artwork"/>
 *         <element ref="{http://musicbrainz.org/ns/mmd-2.0#}count"/>
 *         <element ref="{http://musicbrainz.org/ns/mmd-2.0#}front"/>
 *         <element ref="{http://musicbrainz.org/ns/mmd-2.0#}back"/>
 *         <element ref="{http://musicbrainz.org/ns/mmd-2.0#}darkened" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "artwork",
    "count",
    "front",
    "back",
    "darkened"
})
@XmlRootElement(name = "cover-art-archive")
public class CoverArtArchive {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String artwork;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger count;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String front;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String back;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String darkened;

    /**
     * Gets the value of the artwork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtwork() {
        return artwork;
    }

    /**
     * Sets the value of the artwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtwork(String value) {
        this.artwork = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the front property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFront() {
        return front;
    }

    /**
     * Sets the value of the front property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFront(String value) {
        this.front = value;
    }

    /**
     * Gets the value of the back property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBack() {
        return back;
    }

    /**
     * Sets the value of the back property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBack(String value) {
        this.back = value;
    }

    /**
     * Gets the value of the darkened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDarkened() {
        return darkened;
    }

    /**
     * Sets the value of the darkened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDarkened(String value) {
        this.darkened = value;
    }

}
