//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicbrainz.mmd2;

import java.math.BigInteger;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.musicbrainz.mmd2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Name_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "name");
    private static final QName _SortName_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "sort-name");
    private static final QName _Country_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "country");
    private static final QName _Area_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "area");
    private static final QName _BeginArea_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "begin-area");
    private static final QName _EndArea_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "end-area");
    private static final QName _Entity_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "entity");
    private static final QName _Text_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "text");
    private static final QName _Disambiguation_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "disambiguation");
    private static final QName _Ipi_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "ipi");
    private static final QName _Isni_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "isni");
    private static final QName _Begin_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "begin");
    private static final QName _End_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "end");
    private static final QName _Ended_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "ended");
    private static final QName _Title_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "title");
    private static final QName _Length_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "length");
    private static final QName _Video_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "video");
    private static final QName _FirstReleaseDate_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "first-release-date");
    private static final QName _Quality_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "quality");
    private static final QName _Script_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "script");
    private static final QName _OrderingKey_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "ordering-key");
    private static final QName _Direction_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "direction");
    private static final QName _LabelCode_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "label-code");
    private static final QName _UserRating_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "user-rating");
    private static final QName _Iswc_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "iswc");
    private static final QName _Address_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "address");
    private static final QName _Latitude_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "latitude");
    private static final QName _Longitude_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "longitude");
    private static final QName _Description_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "description");
    private static final QName _Cancelled_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "cancelled");
    private static final QName _Time_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "time");
    private static final QName _Setlist_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "setlist");
    private static final QName _SourceCredit_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "source-credit");
    private static final QName _TargetCredit_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "target-credit");
    private static final QName _Date_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "date");
    private static final QName _Barcode_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "barcode");
    private static final QName _Asin_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "asin");
    private static final QName _Artwork_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "artwork");
    private static final QName _Count_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "count");
    private static final QName _Front_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "front");
    private static final QName _Back_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "back");
    private static final QName _Darkened_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "darkened");
    private static final QName _CatalogNumber_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "catalog-number");
    private static final QName _TrackCount_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "track-count");
    private static final QName _Position_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "position");
    private static final QName _Sectors_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "sectors");
    private static final QName _Pregap_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "pregap");
    private static final QName _Resource_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "resource");
    private static final QName _MemberSince_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "member-since");
    private static final QName _Privs_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "privs");
    private static final QName _Age_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "age");
    private static final QName _Homepage_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "homepage");
    private static final QName _Bio_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "bio");
    private static final QName _EditsAccepted_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "edits-accepted");
    private static final QName _EditsRejected_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "edits-rejected");
    private static final QName _AutoEditsAccepted_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "auto-edits-accepted");
    private static final QName _EditsFailed_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "edits-failed");
    private static final QName _Category_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "category");
    private static final QName _Year_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "year");
    private static final QName _EditNote_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "edit-note");
    private static final QName _Number_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "number");
    private static final QName _Iso31661Code_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "iso-3166-1-code");
    private static final QName _Iso31662Code_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "iso-3166-2-code");
    private static final QName _Iso31663Code_QNAME = new QName("http://musicbrainz.org/ns/mmd-2.0#", "iso-3166-3-code");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.musicbrainz.mmd2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Relation }
     * 
     * @return
     *     the new instance of {@link Relation }
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link LanguageList }
     * 
     * @return
     *     the new instance of {@link LanguageList }
     */
    public LanguageList createLanguageList() {
        return new LanguageList();
    }

    /**
     * Create an instance of {@link Work }
     * 
     * @return
     *     the new instance of {@link Work }
     */
    public Work createWork() {
        return new Work();
    }

    /**
     * Create an instance of {@link Event }
     * 
     * @return
     *     the new instance of {@link Event }
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Medium }
     * 
     * @return
     *     the new instance of {@link Medium }
     */
    public Medium createMedium() {
        return new Medium();
    }

    /**
     * Create an instance of {@link Cdstub }
     * 
     * @return
     *     the new instance of {@link Cdstub }
     */
    public Cdstub createCdstub() {
        return new Cdstub();
    }

    /**
     * Create an instance of {@link Cdstub.TrackList }
     * 
     * @return
     *     the new instance of {@link Cdstub.TrackList }
     */
    public Cdstub.TrackList createCdstubTrackList() {
        return new Cdstub.TrackList();
    }

    /**
     * Create an instance of {@link Work.AttributeList }
     * 
     * @return
     *     the new instance of {@link Work.AttributeList }
     */
    public Work.AttributeList createWorkAttributeList() {
        return new Work.AttributeList();
    }

    /**
     * Create an instance of {@link Relation.AttributeList }
     * 
     * @return
     *     the new instance of {@link Relation.AttributeList }
     */
    public Relation.AttributeList createRelationAttributeList() {
        return new Relation.AttributeList();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     * @return
     *     the new instance of {@link Metadata }
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Artist }
     * 
     * @return
     *     the new instance of {@link Artist }
     */
    public Artist createArtist() {
        return new Artist();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     * @return
     *     the new instance of {@link Gender }
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link DefAreaElementInner }
     * 
     * @return
     *     the new instance of {@link DefAreaElementInner }
     */
    public DefAreaElementInner createDefAreaElementInner() {
        return new DefAreaElementInner();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     * @return
     *     the new instance of {@link Annotation }
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link IpiList }
     * 
     * @return
     *     the new instance of {@link IpiList }
     */
    public IpiList createIpiList() {
        return new IpiList();
    }

    /**
     * Create an instance of {@link IsniList }
     * 
     * @return
     *     the new instance of {@link IsniList }
     */
    public IsniList createIsniList() {
        return new IsniList();
    }

    /**
     * Create an instance of {@link org.musicbrainz.mmd2.LifeSpan }
     * 
     * @return
     *     the new instance of {@link org.musicbrainz.mmd2.LifeSpan }
     */
    public org.musicbrainz.mmd2.LifeSpan createLifeSpan() {
        return new org.musicbrainz.mmd2.LifeSpan();
    }

    /**
     * Create an instance of {@link AliasList }
     * 
     * @return
     *     the new instance of {@link AliasList }
     */
    public AliasList createAliasList() {
        return new AliasList();
    }

    /**
     * Create an instance of {@link Alias }
     * 
     * @return
     *     the new instance of {@link Alias }
     */
    public Alias createAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link RecordingList }
     * 
     * @return
     *     the new instance of {@link RecordingList }
     */
    public RecordingList createRecordingList() {
        return new RecordingList();
    }

    /**
     * Create an instance of {@link Recording }
     * 
     * @return
     *     the new instance of {@link Recording }
     */
    public Recording createRecording() {
        return new Recording();
    }

    /**
     * Create an instance of {@link ArtistCredit }
     * 
     * @return
     *     the new instance of {@link ArtistCredit }
     */
    public ArtistCredit createArtistCredit() {
        return new ArtistCredit();
    }

    /**
     * Create an instance of {@link NameCredit }
     * 
     * @return
     *     the new instance of {@link NameCredit }
     */
    public NameCredit createNameCredit() {
        return new NameCredit();
    }

    /**
     * Create an instance of {@link ReleaseList }
     * 
     * @return
     *     the new instance of {@link ReleaseList }
     */
    public ReleaseList createReleaseList() {
        return new ReleaseList();
    }

    /**
     * Create an instance of {@link Release }
     * 
     * @return
     *     the new instance of {@link Release }
     */
    public Release createRelease() {
        return new Release();
    }

    /**
     * Create an instance of {@link Status }
     * 
     * @return
     *     the new instance of {@link Status }
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Packaging }
     * 
     * @return
     *     the new instance of {@link Packaging }
     */
    public Packaging createPackaging() {
        return new Packaging();
    }

    /**
     * Create an instance of {@link TextRepresentation }
     * 
     * @return
     *     the new instance of {@link TextRepresentation }
     */
    public TextRepresentation createTextRepresentation() {
        return new TextRepresentation();
    }

    /**
     * Create an instance of {@link ReleaseGroup }
     * 
     * @return
     *     the new instance of {@link ReleaseGroup }
     */
    public ReleaseGroup createReleaseGroup() {
        return new ReleaseGroup();
    }

    /**
     * Create an instance of {@link PrimaryType }
     * 
     * @return
     *     the new instance of {@link PrimaryType }
     */
    public PrimaryType createPrimaryType() {
        return new PrimaryType();
    }

    /**
     * Create an instance of {@link SecondaryTypeList }
     * 
     * @return
     *     the new instance of {@link SecondaryTypeList }
     */
    public SecondaryTypeList createSecondaryTypeList() {
        return new SecondaryTypeList();
    }

    /**
     * Create an instance of {@link SecondaryType }
     * 
     * @return
     *     the new instance of {@link SecondaryType }
     */
    public SecondaryType createSecondaryType() {
        return new SecondaryType();
    }

    /**
     * Create an instance of {@link RelationList }
     * 
     * @return
     *     the new instance of {@link RelationList }
     */
    public RelationList createRelationList() {
        return new RelationList();
    }

    /**
     * Create an instance of {@link Target }
     * 
     * @return
     *     the new instance of {@link Target }
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Label }
     * 
     * @return
     *     the new instance of {@link Label }
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link TagList }
     * 
     * @return
     *     the new instance of {@link TagList }
     */
    public TagList createTagList() {
        return new TagList();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     * @return
     *     the new instance of {@link Tag }
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link UserTagList }
     * 
     * @return
     *     the new instance of {@link UserTagList }
     */
    public UserTagList createUserTagList() {
        return new UserTagList();
    }

    /**
     * Create an instance of {@link UserTag }
     * 
     * @return
     *     the new instance of {@link UserTag }
     */
    public UserTag createUserTag() {
        return new UserTag();
    }

    /**
     * Create an instance of {@link GenreList }
     * 
     * @return
     *     the new instance of {@link GenreList }
     */
    public GenreList createGenreList() {
        return new GenreList();
    }

    /**
     * Create an instance of {@link Genre }
     * 
     * @return
     *     the new instance of {@link Genre }
     */
    public Genre createGenre() {
        return new Genre();
    }

    /**
     * Create an instance of {@link UserGenreList }
     * 
     * @return
     *     the new instance of {@link UserGenreList }
     */
    public UserGenreList createUserGenreList() {
        return new UserGenreList();
    }

    /**
     * Create an instance of {@link UserGenre }
     * 
     * @return
     *     the new instance of {@link UserGenre }
     */
    public UserGenre createUserGenre() {
        return new UserGenre();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     * @return
     *     the new instance of {@link Rating }
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link LanguageList.Language }
     * 
     * @return
     *     the new instance of {@link LanguageList.Language }
     */
    public LanguageList.Language createLanguageListLanguage() {
        return new LanguageList.Language();
    }

    /**
     * Create an instance of {@link IswcList }
     * 
     * @return
     *     the new instance of {@link IswcList }
     */
    public IswcList createIswcList() {
        return new IswcList();
    }

    /**
     * Create an instance of {@link Place }
     * 
     * @return
     *     the new instance of {@link Place }
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     * @return
     *     the new instance of {@link Coordinates }
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Instrument }
     * 
     * @return
     *     the new instance of {@link Instrument }
     */
    public Instrument createInstrument() {
        return new Instrument();
    }

    /**
     * Create an instance of {@link Series }
     * 
     * @return
     *     the new instance of {@link Series }
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link Event.LifeSpan }
     * 
     * @return
     *     the new instance of {@link Event.LifeSpan }
     */
    public Event.LifeSpan createEventLifeSpan() {
        return new Event.LifeSpan();
    }

    /**
     * Create an instance of {@link ReleaseEventList }
     * 
     * @return
     *     the new instance of {@link ReleaseEventList }
     */
    public ReleaseEventList createReleaseEventList() {
        return new ReleaseEventList();
    }

    /**
     * Create an instance of {@link ReleaseEvent }
     * 
     * @return
     *     the new instance of {@link ReleaseEvent }
     */
    public ReleaseEvent createReleaseEvent() {
        return new ReleaseEvent();
    }

    /**
     * Create an instance of {@link CoverArtArchive }
     * 
     * @return
     *     the new instance of {@link CoverArtArchive }
     */
    public CoverArtArchive createCoverArtArchive() {
        return new CoverArtArchive();
    }

    /**
     * Create an instance of {@link LabelInfoList }
     * 
     * @return
     *     the new instance of {@link LabelInfoList }
     */
    public LabelInfoList createLabelInfoList() {
        return new LabelInfoList();
    }

    /**
     * Create an instance of {@link LabelInfo }
     * 
     * @return
     *     the new instance of {@link LabelInfo }
     */
    public LabelInfo createLabelInfo() {
        return new LabelInfo();
    }

    /**
     * Create an instance of {@link MediumList }
     * 
     * @return
     *     the new instance of {@link MediumList }
     */
    public MediumList createMediumList() {
        return new MediumList();
    }

    /**
     * Create an instance of {@link Format }
     * 
     * @return
     *     the new instance of {@link Format }
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link DiscList }
     * 
     * @return
     *     the new instance of {@link DiscList }
     */
    public DiscList createDiscList() {
        return new DiscList();
    }

    /**
     * Create an instance of {@link Disc }
     * 
     * @return
     *     the new instance of {@link Disc }
     */
    public Disc createDisc() {
        return new Disc();
    }

    /**
     * Create an instance of {@link OffsetList }
     * 
     * @return
     *     the new instance of {@link OffsetList }
     */
    public OffsetList createOffsetList() {
        return new OffsetList();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     * @return
     *     the new instance of {@link Offset }
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link DefTrackData }
     * 
     * @return
     *     the new instance of {@link DefTrackData }
     */
    public DefTrackData createDefTrackData() {
        return new DefTrackData();
    }

    /**
     * Create an instance of {@link Medium.TrackList }
     * 
     * @return
     *     the new instance of {@link Medium.TrackList }
     */
    public Medium.TrackList createMediumTrackList() {
        return new Medium.TrackList();
    }

    /**
     * Create an instance of {@link DataTrackList }
     * 
     * @return
     *     the new instance of {@link DataTrackList }
     */
    public DataTrackList createDataTrackList() {
        return new DataTrackList();
    }

    /**
     * Create an instance of {@link CollectionList }
     * 
     * @return
     *     the new instance of {@link CollectionList }
     */
    public CollectionList createCollectionList() {
        return new CollectionList();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     * @return
     *     the new instance of {@link Collection }
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link AreaList }
     * 
     * @return
     *     the new instance of {@link AreaList }
     */
    public AreaList createAreaList() {
        return new AreaList();
    }

    /**
     * Create an instance of {@link ArtistList }
     * 
     * @return
     *     the new instance of {@link ArtistList }
     */
    public ArtistList createArtistList() {
        return new ArtistList();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     * @return
     *     the new instance of {@link EventList }
     */
    public EventList createEventList() {
        return new EventList();
    }

    /**
     * Create an instance of {@link InstrumentList }
     * 
     * @return
     *     the new instance of {@link InstrumentList }
     */
    public InstrumentList createInstrumentList() {
        return new InstrumentList();
    }

    /**
     * Create an instance of {@link LabelList }
     * 
     * @return
     *     the new instance of {@link LabelList }
     */
    public LabelList createLabelList() {
        return new LabelList();
    }

    /**
     * Create an instance of {@link PlaceList }
     * 
     * @return
     *     the new instance of {@link PlaceList }
     */
    public PlaceList createPlaceList() {
        return new PlaceList();
    }

    /**
     * Create an instance of {@link ReleaseGroupList }
     * 
     * @return
     *     the new instance of {@link ReleaseGroupList }
     */
    public ReleaseGroupList createReleaseGroupList() {
        return new ReleaseGroupList();
    }

    /**
     * Create an instance of {@link SeriesList }
     * 
     * @return
     *     the new instance of {@link SeriesList }
     */
    public SeriesList createSeriesList() {
        return new SeriesList();
    }

    /**
     * Create an instance of {@link WorkList }
     * 
     * @return
     *     the new instance of {@link WorkList }
     */
    public WorkList createWorkList() {
        return new WorkList();
    }

    /**
     * Create an instance of {@link PuidList }
     * 
     * @return
     *     the new instance of {@link PuidList }
     */
    public PuidList createPuidList() {
        return new PuidList();
    }

    /**
     * Create an instance of {@link Puid }
     * 
     * @return
     *     the new instance of {@link Puid }
     */
    public Puid createPuid() {
        return new Puid();
    }

    /**
     * Create an instance of {@link IsrcList }
     * 
     * @return
     *     the new instance of {@link IsrcList }
     */
    public IsrcList createIsrcList() {
        return new IsrcList();
    }

    /**
     * Create an instance of {@link Isrc }
     * 
     * @return
     *     the new instance of {@link Isrc }
     */
    public Isrc createIsrc() {
        return new Isrc();
    }

    /**
     * Create an instance of {@link Url }
     * 
     * @return
     *     the new instance of {@link Url }
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Editor }
     * 
     * @return
     *     the new instance of {@link Editor }
     */
    public Editor createEditor() {
        return new Editor();
    }

    /**
     * Create an instance of {@link EditInformation }
     * 
     * @return
     *     the new instance of {@link EditInformation }
     */
    public EditInformation createEditInformation() {
        return new EditInformation();
    }

    /**
     * Create an instance of {@link UrlList }
     * 
     * @return
     *     the new instance of {@link UrlList }
     */
    public UrlList createUrlList() {
        return new UrlList();
    }

    /**
     * Create an instance of {@link AnnotationList }
     * 
     * @return
     *     the new instance of {@link AnnotationList }
     */
    public AnnotationList createAnnotationList() {
        return new AnnotationList();
    }

    /**
     * Create an instance of {@link CdstubList }
     * 
     * @return
     *     the new instance of {@link CdstubList }
     */
    public CdstubList createCdstubList() {
        return new CdstubList();
    }

    /**
     * Create an instance of {@link FreedbDiscList }
     * 
     * @return
     *     the new instance of {@link FreedbDiscList }
     */
    public FreedbDiscList createFreedbDiscList() {
        return new FreedbDiscList();
    }

    /**
     * Create an instance of {@link FreedbDisc }
     * 
     * @return
     *     the new instance of {@link FreedbDisc }
     */
    public FreedbDisc createFreedbDisc() {
        return new FreedbDisc();
    }

    /**
     * Create an instance of {@link EditorList }
     * 
     * @return
     *     the new instance of {@link EditorList }
     */
    public EditorList createEditorList() {
        return new EditorList();
    }

    /**
     * Create an instance of {@link EntityList }
     * 
     * @return
     *     the new instance of {@link EntityList }
     */
    public EntityList createEntityList() {
        return new EntityList();
    }

    /**
     * Create an instance of {@link Iso31661CodeList }
     * 
     * @return
     *     the new instance of {@link Iso31661CodeList }
     */
    public Iso31661CodeList createIso31661CodeList() {
        return new Iso31661CodeList();
    }

    /**
     * Create an instance of {@link Iso31662CodeList }
     * 
     * @return
     *     the new instance of {@link Iso31662CodeList }
     */
    public Iso31662CodeList createIso31662CodeList() {
        return new Iso31662CodeList();
    }

    /**
     * Create an instance of {@link Iso31663CodeList }
     * 
     * @return
     *     the new instance of {@link Iso31663CodeList }
     */
    public Iso31663CodeList createIso31663CodeList() {
        return new Iso31663CodeList();
    }

    /**
     * Create an instance of {@link Cdstub.TrackList.Track }
     * 
     * @return
     *     the new instance of {@link Cdstub.TrackList.Track }
     */
    public Cdstub.TrackList.Track createCdstubTrackListTrack() {
        return new Cdstub.TrackList.Track();
    }

    /**
     * Create an instance of {@link Work.AttributeList.Attribute }
     * 
     * @return
     *     the new instance of {@link Work.AttributeList.Attribute }
     */
    public Work.AttributeList.Attribute createWorkAttributeListAttribute() {
        return new Work.AttributeList.Attribute();
    }

    /**
     * Create an instance of {@link Relation.AttributeList.Attribute }
     * 
     * @return
     *     the new instance of {@link Relation.AttributeList.Attribute }
     */
    public Relation.AttributeList.Attribute createRelationAttributeListAttribute() {
        return new Relation.AttributeList.Attribute();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "sort-name")
    public JAXBElement<String> createSortName(String value) {
        return new JAXBElement<>(_SortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "area")
    public JAXBElement<DefAreaElementInner> createArea(DefAreaElementInner value) {
        return new JAXBElement<>(_Area_QNAME, DefAreaElementInner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "begin-area")
    public JAXBElement<DefAreaElementInner> createBeginArea(DefAreaElementInner value) {
        return new JAXBElement<>(_BeginArea_QNAME, DefAreaElementInner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefAreaElementInner }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "end-area")
    public JAXBElement<DefAreaElementInner> createEndArea(DefAreaElementInner value) {
        return new JAXBElement<>(_EndArea_QNAME, DefAreaElementInner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "entity")
    public JAXBElement<String> createEntity(String value) {
        return new JAXBElement<>(_Entity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "disambiguation")
    public JAXBElement<String> createDisambiguation(String value) {
        return new JAXBElement<>(_Disambiguation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "ipi")
    public JAXBElement<String> createIpi(String value) {
        return new JAXBElement<>(_Ipi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "isni")
    public JAXBElement<String> createIsni(String value) {
        return new JAXBElement<>(_Isni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "begin")
    public JAXBElement<String> createBegin(String value) {
        return new JAXBElement<>(_Begin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "end")
    public JAXBElement<String> createEnd(String value) {
        return new JAXBElement<>(_End_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "ended")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEnded(String value) {
        return new JAXBElement<>(_Ended_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "length")
    public JAXBElement<BigInteger> createLength(BigInteger value) {
        return new JAXBElement<>(_Length_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "video")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVideo(String value) {
        return new JAXBElement<>(_Video_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "first-release-date")
    public JAXBElement<String> createFirstReleaseDate(String value) {
        return new JAXBElement<>(_FirstReleaseDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefQuality }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefQuality }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "quality")
    public JAXBElement<DefQuality> createQuality(DefQuality value) {
        return new JAXBElement<>(_Quality_QNAME, DefQuality.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "script")
    public JAXBElement<String> createScript(String value) {
        return new JAXBElement<>(_Script_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "ordering-key")
    public JAXBElement<BigInteger> createOrderingKey(BigInteger value) {
        return new JAXBElement<>(_OrderingKey_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefDirection }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefDirection }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "direction")
    public JAXBElement<DefDirection> createDirection(DefDirection value) {
        return new JAXBElement<>(_Direction_QNAME, DefDirection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "label-code")
    public JAXBElement<BigInteger> createLabelCode(BigInteger value) {
        return new JAXBElement<>(_LabelCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "user-rating")
    public JAXBElement<BigInteger> createUserRating(BigInteger value) {
        return new JAXBElement<>(_UserRating_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "iswc")
    public JAXBElement<String> createIswc(String value) {
        return new JAXBElement<>(_Iswc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "latitude")
    public JAXBElement<String> createLatitude(String value) {
        return new JAXBElement<>(_Latitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "longitude")
    public JAXBElement<String> createLongitude(String value) {
        return new JAXBElement<>(_Longitude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "cancelled")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCancelled(String value) {
        return new JAXBElement<>(_Cancelled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "setlist")
    public JAXBElement<String> createSetlist(String value) {
        return new JAXBElement<>(_Setlist_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "source-credit")
    public JAXBElement<String> createSourceCredit(String value) {
        return new JAXBElement<>(_SourceCredit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "target-credit")
    public JAXBElement<String> createTargetCredit(String value) {
        return new JAXBElement<>(_TargetCredit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "barcode")
    public JAXBElement<String> createBarcode(String value) {
        return new JAXBElement<>(_Barcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "asin")
    public JAXBElement<String> createAsin(String value) {
        return new JAXBElement<>(_Asin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "artwork")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArtwork(String value) {
        return new JAXBElement<>(_Artwork_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "count")
    public JAXBElement<BigInteger> createCount(BigInteger value) {
        return new JAXBElement<>(_Count_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "front")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFront(String value) {
        return new JAXBElement<>(_Front_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "back")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBack(String value) {
        return new JAXBElement<>(_Back_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "darkened")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDarkened(String value) {
        return new JAXBElement<>(_Darkened_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "catalog-number")
    public JAXBElement<String> createCatalogNumber(String value) {
        return new JAXBElement<>(_CatalogNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "track-count")
    public JAXBElement<BigInteger> createTrackCount(BigInteger value) {
        return new JAXBElement<>(_TrackCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "position")
    public JAXBElement<BigInteger> createPosition(BigInteger value) {
        return new JAXBElement<>(_Position_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "sectors")
    public JAXBElement<BigInteger> createSectors(BigInteger value) {
        return new JAXBElement<>(_Sectors_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefTrackData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DefTrackData }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "pregap")
    public JAXBElement<DefTrackData> createPregap(DefTrackData value) {
        return new JAXBElement<>(_Pregap_QNAME, DefTrackData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "resource")
    public JAXBElement<String> createResource(String value) {
        return new JAXBElement<>(_Resource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "member-since")
    public JAXBElement<String> createMemberSince(String value) {
        return new JAXBElement<>(_MemberSince_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "privs")
    public JAXBElement<BigInteger> createPrivs(BigInteger value) {
        return new JAXBElement<>(_Privs_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "age")
    public JAXBElement<String> createAge(String value) {
        return new JAXBElement<>(_Age_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "homepage")
    public JAXBElement<String> createHomepage(String value) {
        return new JAXBElement<>(_Homepage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "bio")
    public JAXBElement<String> createBio(String value) {
        return new JAXBElement<>(_Bio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "edits-accepted")
    public JAXBElement<BigInteger> createEditsAccepted(BigInteger value) {
        return new JAXBElement<>(_EditsAccepted_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "edits-rejected")
    public JAXBElement<BigInteger> createEditsRejected(BigInteger value) {
        return new JAXBElement<>(_EditsRejected_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "auto-edits-accepted")
    public JAXBElement<BigInteger> createAutoEditsAccepted(BigInteger value) {
        return new JAXBElement<>(_AutoEditsAccepted_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "edits-failed")
    public JAXBElement<BigInteger> createEditsFailed(BigInteger value) {
        return new JAXBElement<>(_EditsFailed_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "category")
    public JAXBElement<String> createCategory(String value) {
        return new JAXBElement<>(_Category_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "year")
    public JAXBElement<String> createYear(String value) {
        return new JAXBElement<>(_Year_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "edit-note")
    public JAXBElement<String> createEditNote(String value) {
        return new JAXBElement<>(_EditNote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "iso-3166-1-code")
    public JAXBElement<String> createIso31661Code(String value) {
        return new JAXBElement<>(_Iso31661Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "iso-3166-2-code")
    public JAXBElement<String> createIso31662Code(String value) {
        return new JAXBElement<>(_Iso31662Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://musicbrainz.org/ns/mmd-2.0#", name = "iso-3166-3-code")
    public JAXBElement<String> createIso31663Code(String value) {
        return new JAXBElement<>(_Iso31663Code_QNAME, String.class, null, value);
    }

}
