//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 08:05:28 AM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://musicbrainz.org/ns/mmd-2.0#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.musicbrainz.mmd2;
