//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 02:40:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://musicbrainz.org/ns/mmd-2.0#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.musicbrainz.mmd2;
